# Generated by Django 5.2.5 on 2025-09-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_student_department_remove_student_is_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='department',
        ),
    ]
