# Generated by Django 5.2.5 on 2025-09-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_name_department_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='pics',
            field=models.ImageField(blank=True, null=True, upload_to='data/'),
        ),
    ]
